**INSTALACION DE PANDAS**

In [13]:
!pip install pandas
!pip install openpyxl

Requirement already satisfied: pandas in c:\users\chivox\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\chivox\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\chivox\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\chivox\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\chivox\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\chivox\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: openpyxl in c:\users\chivox\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\chivox\anaconda3\lib\site-packages (from openpyxl) (2.0.0)

**TALLER N1*

In [ ]:
import pandas as pd
import numpy as np

In [23]:
datos_excel = pd.read_excel("Libro22.xlsx")

In [26]:
datos_excel

,C.O.,Nro documento,Fecha,Estado,Razón social cliente factura,Bodega,Item,Referencia,Desc. item,U.M. inv.,Cantidad inv.,Valor subtotal
0,B16,FPO-00007507,2025-07-04,Aprobado,NaN,B16,2862,2862,VENTA JARRA MIXIRIPA - BOTELLA,UND,1,42101
1,B16,FPO-00007499,2025-07-04,Aprobado,NaN,B16,2862,2862,VENTA JARRA MIXIRIPA - BOTELLA,UND,1,42101
2,B16,FPO-00007494,2025-07-04,Aprobado,NaN,B16,237,237,PROPINAS,UND,1,2958
3,B16,FPO-00007518,2025-07-04,Aprobado,NaN,B16,1889,1889,VENTA AGUA SIN GAS PASANTE,UND,2,14000
4,B16,FPO-00007509,2025-07-04,Aprobado,NaN,B16,10,10,CERVEZA CAJICA JARRA,UND,1,39916
...,...,...,...,...,...,...,...,...,...,...,...,...
20623,B16,FPO-00004809,2025-02-12,Aprobado,NaN,B16,899,899,VENTA LICOR WHISKY OLD PARR TRAGO,UND,2,46387
20624,B16,FPO-00004805,2025-02-12,Aprobado,NaN,B16,237,237,PROPINAS,UND,1,903
20625,B16,FPO-00004823,2025-02-13,Aprobado,NaN,B16,51,51,CERVEZA SEPTIMAZO JARRA,UND,4,152182
20626,B16,FPO-00004828,2025-02-13,Aprobado,NaN,B16,9,9,CERVEZA CAJICA PINTA,UND,10,129237
20627,B16,FPO-00004833,2025-02-13,Aprobado,NaN,B16,4,4,CERVEZA BACATA PINTA,UND,2,24890

**VENTAS TOTAL POR MES**

In [70]:

datos_excel["Valor subtotal "].sum()

np.int64(481666542)

In [97]:
datos_excel["Fecha"] = pd.to_datetime(datos_excel["Fecha"])
datos_excel["Mes"] = datos_excel["Fecha"]. dt.to_period ("M")
ventas_mensuales = datos_excel.groupby(datos_excel["Fecha"].dt.to_period("M"))["Valor subtotal "].sum()
ventas_mensuales

Fecha
2025-01    26913023
2025-02    33465424
2025-03    35370338
2025-04    38595736
2025-05    44971169
2025-06    39124254
2025-07    46758070
2025-08    46926979
2025-09    40857514
2025-10    49158537
2025-11    45176236
2025-12    34349262
Freq: M, Name: Valor subtotal , dtype: int64

**¿CUAL ES EL PROMEDIO MENSUAL?**

In [266]:
ventas_mensuales.mean()

np.float64(40138878.5)

**¿PUEDES MOSTRARME LAS VENTAS ANUALES DE MANERA DESENDIENTES ?**

In [202]:
meses_mas_rentables = datos_excel.groupby(datos_excel["Fecha"].dt.to_period("M"))["Valor subtotal "].sum()
meses_mas_rentables = datos_excel.groupby(datos_excel["Fecha"].dt.to_period("M"))["Valor subtotal "].sum().sort_values(ascending=False)
meses_mas_rentables

Fecha
2025-10    49158537
2025-08    46926979
2025-07    46758070
2025-11    45176236
2025-05    44971169
2025-09    40857514
2025-06    39124254
2025-04    38595736
2025-03    35370338
2025-12    34349262
2025-02    33465424
2025-01    26913023
Freq: M, Name: Valor subtotal , dtype: int64

**MUESTRAME LOS 5 PRODUCTOS MAS VENDIDOS Y QUE HAN GENERADO MAYORES INGRESOS EN TODO EL AÑO?**

In [180]:

datos_excel.groupby(['Desc. item'])[['Cantidad inv.','Valor subtotal ']].sum()

                                    Cantidad inv.  Valor subtotal
Desc. item
AGUA MANANTIAL CON GAS 600ML                  126           809996
BLACK N TAN JARRA CP MR                         3           102732
BLACK N TAN PINTA                               1            14144
CERVEZA BACATA BOTELLA 330                    312          2836283
CERVEZA BACATA BOTELLA PARA LLEVAR            204          1517459
...                                           ...              ...
VENTA VEEV NOW STRAWBERRY 1800                  2            72100
VENTA VEEV NOW ULTRA APPLE                      2            55294
VENTA VEEV NOW ULTRA MI                         3            82941
VENTA VEEV NOW WATERMELON 1800                  2            72100
VENTA ZYN BLACK CHERRY                          2            28402

[167 rows x 2 columns]

In [263]:
top_5 = datos_excel.groupby(['Desc. item'])[['Cantidad inv.','Valor subtotal ']].sum()
top_5 = datos_excel.groupby(['Desc. item'])[['Cantidad inv.', 'Valor subtotal ']].sum().nlargest(6, 'Valor subtotal ')

print(top_5)

                                          Cantidad inv.  Valor subtotal
Desc. item
CERVEZA CAJICA JARRA                               3916        152575304
PROPINAS                                           6143         41711824
CERVEZA CAJICA PINTA                               2053         28798376
CERVEZA MONSERRATE JARRA                            515         19818942
VENTA JARRA BBC ROSE                                456         17488080
VENTA ALITAS X 10 + CRIOLLA                         467         14810987

In [ ]:

top_5 = datos_excel.groupby(['Desc. item'])[['Cantidad inv.', 'Valor subtotal ']].sum().nlargest(6, 'Valor subtotal ')
top_5 = top_5.drop('PROPINAS')

print(top_5)

                                          Cantidad inv.  Valor subtotal
Desc. item
CERVEZA CAJICA JARRA                               3916        152575304
CERVEZA CAJICA PINTA                               2053         28798376
CERVEZA MONSERRATE JARRA                            515         19818942
VENTA JARRA BBC ROSE                                456         17488080
VENTA ALITAS X 10 + CRIOLLA                         467         14810987

**CALCULA EL TICKE PROMEDIO**

In [269]:
total_ventas = datos_excel['Valor subtotal '].sum()
cantidad_facturas = len(datos_excel)
ticket_promedio = total_ventas / cantidad_facturas

print(ticket_promedio)

23350.132926119837

**CONCLUSIONES** 

  1. SE NOTA UN COMPORTAMIENTO ESTACIONAL AL ANALIZAR LAS VENTAS MENSUALES, YA QUE SE MUESTRA, UN INICIO DE AÑO SUAVE ARRANCANDO CON UNOS 26.9M EN ENERO EL CUAL ALCANZA SU PICO EN OCTUBRE (49.1M) Y YA PARA DICEMBRE DECAE A 34.3M LO QUE ES ATIPICO PARA UNA CERVECERIA POR SER TEMPORADA ALTA.

  2. EL PRODUCTO TOP EN VENTAS ES LA CERVECA CAJICA EN JARRA SOBRE LA PINTA DESMOSTRANDO QUE EL PUBLICO VALORA LA EXPERIENCIOA DE COMPARTIR Y EL AHORRO POR VOLUMEN.

  3. CON EL CALCULO DEL PROMEDIO MENSUAL (40M) SE REFLEJA QUE LA CERVECERIA MANTIEN UN RITMO DE NEGOCIO SOLIDO PARA UN LOCAL MEDIANO EN BOGOTA 

  4. EL TICKE PROMEDIO REFLEJA LO QUE CONSUME UN CLIENTE AL ENTRAR AL LOCAL, POR ENDE, TOCA MEJORAR ESTE NUMERO NO SOLO ATRAYENDO MAS CLIENTES SI NO BRINDANDO UNA MEJOR EXPERIENCIA DE VENTA CON LO QUE YA SE TIENE 
     
     DOS ESTRATTEGIAS PARA ALCANZAR ESTA META SERIA: 

     +La Regla del "Combo" (Cross-selling):
Si el cliente ya pidió la Cerveza el mesero debe estar entrenado para ofrecer el "Acompañamiento Ideal". Si logras que un 30% de tus clientes acepten, tu ticket promedio subirá de inmediato.

      +Upselling (Venta de gama superior):
Si tienes una cerveza premium o un formato más grande, es el momento de ofrecerlo cuando el cliente duda en su pedido.